name: testing workspace usage
on: 
  workflow_dispatch:
  
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - run: node --version
        name: Check Node verion
      - name: create txt file
        run: |
          echo "hello world" >> "${{github.workspace }}/data.txt"
          ls -la
          cat "${{github_workspace }}/data.txt"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps: 
      - run: |
          ls -la
          cat "${{github.workspace }}/data.txt"
        name: print the data 
    
    
      
