name: Share data between jobs

on:
  pull_request:
    types: [synchronize]
  issue_comment:

jobs:
  cypress_tests:
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.body, 'test this please')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        subset: ["1", "2", "3","4"]
    steps:
      - shell: bash
        run: |
          mkdir -p coverage/${{ matrix.subset }} 
          mkdir -p test_coverage
          cd test_coverage
          expr 3 + 7 > math-homework.txt
          cd ..
          cp -R test_coverage/math-homework.txt coverage/${{ matrix.subset }}   # Move coverage report to shared directory
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.subset }}
          path: coverage
  job_2:
    name: Multiply by 9
    needs: cypress_tests
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          merge-multiple: true
      - shell: bash
        run: |
          ls -la
          cd 1
          value=`cat math-homework.txt`
          expr $value \* 9 > math-homework.txt
          echo The result is $value
