name: testing workspace usage
'on': 
  push:
  workflow_dispatch:
  
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check Node verion
        run: node --version
      - name: create txt file
        run: |
          echo "hello world"
          ls -la
