name: testing workspace usage
'on': 
  push
  workflow_dispatch:
  
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check Node verion
        run: node --version
      - name: create txt file
        run: |
          echo "hello world" > "${{github.workspace }}/data.txt"
          ls -la
          cat "${{github_workspace }}/data.txt"

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps: 
      - name: print the data 
        run: |
          ls -la
          cat "${{github.workspace }}/data.txt"
